apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: gateway-operator
build:
  tagPolicy:
    inputDigest: {}
manifests:
  kustomize:
    paths:
    - config/default
deploy:
  kubectl:
    flags:
      apply:
        - --server-side
profiles:
- name: default
  manifests:
    kustomize:
      paths:
      - config/default
      - config/crd
  build:
    artifacts:
    - image: docker.io/kong/gateway-operator
      docker:
        dockerfile: Dockerfile
        target: distroless
        buildArgs:
          TAG: ${{ .TAG }}
          COMMIT: ${{ .COMMIT }}
          REPO_INFO: ${{ .REPO_INFO }}
- name: dev
  manifests:
    kustomize:
      paths:
      - config/dev
      - config/crd
  build:
    artifacts:
    - image: docker.io/kong/gateway-operator
      docker:
        dockerfile: Dockerfile
        target: distroless
        buildArgs:
          TAG: ${{ .TAG }}
          COMMIT: ${{ .COMMIT }}
          REPO_INFO: ${{ .REPO_INFO }}
- name: debug
  manifests:
    kustomize:
      paths:
      - config/debug
      - config/crd
  build:
    artifacts:
    - image: docker.io/kong/gateway-operator
      docker:
        dockerfile: debug.Dockerfile
        target: debug
        buildArgs:
          TAG: ${{ .TAG }}
          COMMIT: ${{ .COMMIT }}
          REPO_INFO: ${{ .REPO_INFO }}
