name: Build container image
# This run-name will contain the branch name when run with pull_request or
# pull_request_target event.
# Otherwise it will contain the tag name if present or SHA.
run-name: Build container image ${{ github.head_ref || ( github.ref_type == 'tag' && github.ref_name || github.sha ) }}

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || ( github.ref_type == 'tag' && github.ref_name || github.sha ) }}
  cancel-in-progress: true

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    uses: ./.github/workflows/__build-workflow.yaml
    secrets:
      token: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
    with:
      username: ${{ vars.DOCKERHUB_PUSH_USERNAME  }}
      registry: docker.io
      image-name: kong/gateway-operator
      push: true
