name: nightly

on:
  schedule:
    - cron: '30 3 * * *'
  workflow_dispatch: {}

jobs:
  build-push-images:
    uses: ./.github/workflows/__build-workflow.yaml
    secrets:
      token: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
    with:
      username: ${{ vars.DOCKERHUB_PUSH_USERNAME  }}
      registry: docker.io
      image-name: ${{ vars.DOCKERHUB_IMAGE_NAME }}
      push: true
