# This job is not inteneded to be run manually. Instead it assumes that proper
# release commit is pushed to the repository. It will then create a new release
# on GitHub.
name: release-bot

on:
  push:
    branches:
      - 'main'

jobs:
  look_for_release:
    outputs:
      release_found: ${{ steps.commit_parser.outputs.release_found }}
      release_type: ${{ steps.commit_parser.outputs.release_type }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: search for release command in commit message
        id: commit_parser
        uses: actions/github-script@v7
        with:
          script: |
            const commitMessage = context.payload.head_commit.message
            if (commitMessage.includes('chore(release): [bot]')) {
              core.setOutput('release_found', 'true')
              core.setOutput('release_type', 'release')
            } else if (commitMessage.includes('chore(prerelease): [bot]')) {
              core.setOutput('release_found', 'true')
              core.setOutput('release_type', 'prerelease')
            } else {
              core.setOutput('release_found', 'false')
            }

  semver:
    needs:
      - look_for_release
    if: ${{ needs.look_for_release.outputs.release_found == 'true' }}
    outputs:
      version: ${{ steps.semver_parser.outputs.fullversion }}
      major: ${{ steps.semver_parser.outputs.major }}
      minor: ${{ steps.semver_parser.outputs.minor }}
      patch: ${{ steps.semver_parser.outputs.patch }}
      prerelease: ${{ steps.semver_parser.outputs.prerelease }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Read version from VERSION file
        run: |
          VERSION=$(cat VERSION)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1.4.7
        with:
          input_string: ${{ env.VERSION }}
          version_extractor_regex: '(.*)$'

      - name: check if tag already exists
        uses: mukunku/tag-exists-action@v1.5.0
        id: tag_exists
        with:
          tag: ${{ steps.commit_parser.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: fail if tag already exists
        if: ${{ steps.tag_exists.outputs.exists == 'true' }}
        run: exit 1

  publish-release:
    needs:
      - look_for_release
      - semver
    if: ${{ needs.look_for_release.outputs.release_found == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
        with:
          body: |
            #### Download Kong Gateway Operator ${{ needs.semver.outputs.version }}:

            - [Docker Image](https://hub.docker.com/r/kong/gateway-operator/tags?name=${{ needs.semver.outputs.version }})
            - [Get started](https://github.com/Kong/gateway-operator/blob/main/README.md)

            #### Links:

            - [Changelog](https://github.com/Kong/gateway-operator/blob/main/CHANGELOG.md#v${{ needs.semver.outputs.major }}${{ needs.semver.outputs.minor }}${{ needs.semver.outputs.patch }}${{ needs.semver.outputs.prerelease }})

          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ needs.semver.outputs.version }}
          commit: ${{ github.sha }}
          prerelease: ${{ needs.look_for_release.outputs.release_type == 'prerelease' }}

  create-gateway-operator-docs-pull-request:
    needs:
      - look_for_release
      - publish-release
      - semver
    if: ${{ needs.look_for_release.outputs.release_found == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Kong/gateway-operator-docs repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: Kong/gateway-operator-docs
          path: gateway-operator-docs

      - name: Update docs repo with new release
        run: |
          rm -rf gateway-operator-docs/config
          cp -r config gateway-operator-docs
          cp CHANGELOG.md gateway-operator-docs

      - name: GPG sign the commits
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      # Create a PR to update the docs repo with the new release.
      # PR includes the CHANGELOG and config files.
      - name: Create a PR to Kong/gateway-operator-docs
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        with:
          token: ${{ secrets.PAT_GITHUB }}
          path: gateway-operator-docs
          add-paths: |
            config
            CHANGELOG.md
          commit-message: "chore(release): operator kong-gateway-operator (${{ needs.semver.outputs.version }})"
          committer: Kong's Team k8s bot <team-k8s+github-bot@konghq.com>
          author: Kong's Team k8s bot <team-k8s+github-bot@konghq.com>
          base: main
          branch: kong-gateway-operator-${{ github.event.inputs.tag }}
          delete-branch: true
          title: operator kong-gateway-operator (${{ needs.semver.outputs.version }})
          body: operator kong-gateway-operator (${{ needs.semver.outputs.version }})

  create-community-operators-pull-request:
    needs:
      - look_for_release
      - publish-release
      - semver
    if: ${{ needs.look_for_release.outputs.release_found == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Ensure version is set
        env:
          VERSION: ${{ needs.semver.outputs.version }}
        run: |
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo ${VERSION} > VERSION

      - name: Generate bundle
        run: make bundle

      - name: Checkout k8s-operatorhub/community-operators repo
        uses: actions/checkout@v4
        with:
          repository: k8s-operatorhub/community-operators
          path: k8s-operatorhub-community-operators

      - name: Copy the bundle to the k8s-operatorhub-community-operators repo
        # Operator bundles in community-operators do not have a 'v' prefix in directory
        # names so we use the 'v' stripped tag.
        run: |
          mkdir -p k8s-operatorhub-community-operators/operators/kong-gateway-operator/${{ env.VERSION }}
          cp -r bundle/regular/* k8s-operatorhub-community-operators/operators/kong-gateway-operator/${{ env.VERSION }}

      - name: Read PR template from k8s-operatorhub-community-operators/docs/pull_request_template.md
        id: pr-template
        run: |
          echo "PR_TEMPLATE<<EOF" >> $GITHUB_ENV
          cat k8s-operatorhub-community-operators/docs/pull_request_template.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: GPG sign the commits
        uses: crazy-max/ghaction-import-gpg@01dd5d3ca463c7f10f7f4f7b4f177225ac661ee4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Pushes bundle to k8s-operatorhub-community-operators
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38
        id: create_pull_request
        with:
          token: ${{ secrets.PAT_GITHUB }}
          path: k8s-operatorhub-community-operators
          push-to-fork: Kong/k8s-operatorhub-community-operators
          add-paths: operators/kong-gateway-operator/${{ env.VERSION }}
          commit-message: operator kong-gateway-operator (${{ env.VERSION }})
          committer: Kong's Team k8s bot <team-k8s+github-bot@konghq.com>
          author: Kong's Team k8s bot <team-k8s+github-bot@konghq.com>
          signoff: true
          base: main
          branch: kong-gateway-operator-${{ inputs.tag }}
          delete-branch: true
          title: operator kong-gateway-operator (${{ env.VERSION }})
          body: ${{ env.PR_TEMPLATE }}

      - name: Check outputs
        if: ${{ steps.create_pull_request.outputs.pull-request-url }}
        run: |
          echo "Pull Request URL - ${{ steps.create_pull_request.outputs.pull-request-url }}"
