name: release
run-name: "Release ${{ format('{0} (type: {1})', inputs.tag, inputs.release_type) }} "

on:
  workflow_dispatch:
    inputs:
      tag:
        description: The version to release (e.g. v1.2.3)
        required: true
      latest:
        description: Whether to tag this build latest
        type: boolean
        default: false
      release_type:
        description: Whether to make a created release a pre-release
        required: true
        default: 'prerelease'
        type: choice
        options:
        - prerelease
        - release

jobs:
  release:
    uses: ./.github/workflows/__release-workflow.yaml
    secrets:
      dockerhub-push-token: ${{ secrets.DOCKERHUB_PUSH_TOKEN }}
    with:
      dockerhub-push-username: ${{ vars.DOCKERHUB_PUSH_USERNAME  }}
      image-name: kong/gateway-operator-oss
      push: true
      latest: ${{ inputs.latest }}
      tag: ${{ inputs.tag }}
      release_type: ${{ inputs.release_type }}
